name: Go

on: [push]

env:
  GO_VERSION_SUPPORTED: "1.26.x"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [$GO_VERSION_SUPPORTED, "stable"]
        include:
          - goos: windows
            goarch: amd64
            name: windows-x64

          - goos: darwin
            goarch: arm64
            name: macos-arm64

          - goos: linux
            goarch: amd64
            name: linux-x64

          - goos: linux
            goarch: arm64
            name: linux-arm64

    steps:
      - uses: actions/checkout@v6
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0

        run: |
          mkdir -p dist
          
          output="dist/gophermap-${{ matrix.name }}"

          if [ "${{ matrix.goos }}" = "windows" ]; then
            output="${output}.exe"
          fi

          go build \
            -ldflags="-s -w" \
            -trimpath -v \
            -o "$output" cli/main.go

      - uses: actions/upload-artifact@v7
        with:
          path: dist/

      - name: Publish artifact
        if: matrix.go-version == '$GO_VERSION_SUPPORTED'
        uses: actions/upload-artifact@v4
        with:
          name: gophermap-${{ matrix.name }}
          path: dist/
